version: '3'
services:
  web:
    image: php:7.4-apache
    container_name: coffee_house_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:5.7
    container_name: coffee_house_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: coffee_house_db
    ports:
      - "3306:3306"
