version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee_house_web
    ports:
      - "0.0.0.0:9090:80"
    volumes:
      - ./src:/var/www/html/src
      - ./icon:/var/www/html/icon